from_latest_tag = true
ignore_merge_commits = false
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
# Skip global tag (nixkraken releases) for now
# TODO: set to true once release process is done and validated
generate_mono_repository_global_tag = false
generate_mono_repository_package_tags = true
monorepo_version_separator = "/"
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
post_package_bump_hooks = []
pre_package_bump_hooks = [
  "echo 'upgrading {{package}} to {{version}}'",
  ".cog/pre {{latest|1.0.0}} {{version}}"
]

[bump_profiles]

[changelog]
path = "CHANGELOG.md"
template = "full_hash"
authors = [
  {username = "nicolas-goudry", signature = "Nicolas Goudry"}
]

[commit_types]
feat = {changelog_title = "✨ New Features"}
fix = {changelog_title = "🐛 Bug Fixes"}
perf = {changelog_title = "🚀 Performance Improvements"}
docs = {changelog_title = "📚 Documentation Updates"}
test = {changelog_title = "🧪 Tests"}
refactor = {changelog_title = "🧹 Code Refactoring"}
style = {changelog_title = "🎨 Code Style & Formatting"}
# Omit from changelogs
ci = {omit_from_changelog = true}
chore = {omit_from_changelog = true}
# Disable entirely
revert = {}
build = {}

[git_hooks.commit-msg]
script = """#!/usr/bin/env bash
set -e
cog verify --file $1
cog check || true
"""

[git_hooks.pre-push]
script = """#!/usr/bin/env bash
if command -v nix >/dev/null \
  && [ -f /etc/nix/nix.conf ] \
  && [[ "$(grep -E '^experimental-features =' /etc/nix/nix.conf | awk -F'=' '{print $2}' | xargs)" =~ (flakes|nix-commands) ]]
then
  system=$(nix eval --impure --expr "builtins.currentSystem")
  nix build ".#checks.$system.all"
else
  >&2 echo "WARNING: Nix Flakes and/or new commands are not enabled! Evaluation checks will not be performed."
fi
"""

[packages]
deep-json-diff = {path = "gitkraken/utils/deep-json-diff", public_api = false}
docs = {path = "docs", public_api = false}
gitkraken-themes = {path = "themes", public_api = false}
gk-app-extractor = {path = "gitkraken/utils/app-extractor", public_api = false}
gk-config-discovery = {path = "gitkraken/utils/config-discovery", public_api = false}
gk-configure = {path = "pkgs/configure", public_api = true}
gk-decrypt = {path = "pkgs/decrypt", public_api = true}
gk-encrypt = {path = "pkgs/encrypt", public_api = true}
gk-login = {path = "pkgs/login", public_api = true}
gk-theme = {path = "pkgs/theme", public_api = true}
